### ISSUE TITLE
Hint: GitHub Organization named touchegg

### ISSUE THREAD

**Issue by alexandre-mbm** [JoseExposito/touchegg#262]
The its projects would be:
- touchegg (this)
- touchegg-gui
- touchegg-gce (invited)
- touchegg-book (a gitbook multi-language)
- touchegg-conf (config profiles)
- _+ packing projects..._

**Comment by JoseExposito** [comment]
Hi @alexandre-mbm 

I'd prefer to keep the project as simple as possible since there is a long time I don't work on it and Canonical doesn't improve uTouch (I guess because they are focusing on Mir rather than on the X11 or Wayland support).

Touchégg works as it is and I don't plan to add extra features... Wayland will become the standard at some point and them I'll have a look to the options it'll offer... But for the moment it looks like it is not going to be possible to get Touchégg working on it.

Thanks!

**Comment by alexandre-mbm** [comment]
I understand.

Do you can say me if Touchégg supports _touchscreen_ or if it is only for _touchpad_?

**Comment by JoseExposito** [comment]
In theory it does support touchscreen, but I don't have a touchscreen device to test with, so I can not ensure it.
