### ISSUE TITLE
Touchegg On Cinnamon desktop

### ISSUE THREAD

**Issue by RedBow** [JoseExposito/touchegg#269]
On Cinnamon desktop when using certain touchscreens Touchegg seems to hijack the pointer when touching over the panel applets, and the effect will be touchegg acting upon the windows hidden below the panel applet. 

A work around seems to be having touchegg configured for individual apps only. (ex not having an application node for all applications `<application name="ALL">`. so a possible workaround that I (as a fairly inexperienced programmer) considered is having a special name that would let the `config` class read in all the desktop entries in `/usr/share/applications` to the `QHash<QString, QString> settings;` and have entries for desktop combined with each gesture.

I was wondering if you had any better suggestions or concerns

Thanks,
Kimee

**Comment by dbruenig** [comment]
Yes, or similar, you could add an exclusion list to the ALL group on which gestures from ALL are not applied. 

If you could give some more information about the problem with the gestures behind the panel applets (more descriptive, versions, desktop environment, etc) it would help to find where the problem is.

**Comment by Simonmicro** [comment]
The bug is still present in the newest Cinnamon Version, delivered by Linux Mint 19. [Cinnamon 3.8.9] The touchegg version seems to be 1.1.1. The used display manager is lightdm...
I hope that helps.
Simonmicro

**Comment by urbie-mk2** [comment]
I'd say stick to the original suggestion by redbow. Since I did not heard back from him in 2016, I did not bother to investigate any further. 

As a general rule:
0. check configuration and drivers
1. read the source code and find out which components are affected
2. compare the components installed (versions, dependencies) to older versions
3. try older versions of affected components
4. recompile the components if necessary.

I can be of assistance in these steps.

**Comment by Simonmicro** [comment]
Okay, after some first looks I understand the following (correct me if I'm wrog):
1. Touchegg uses Qt to communicate with X11
2. We're listen for window creations/destructions -> if this happens we will grab (or copy) any incoming event and prcess it. The we will pass it back to the window.
3. Hypothetical game:

3.1. The cinnamon panel draws an applet (e.g. volume control) but this applet gets not registered to cinnamons panel "window" - instead it will be simply drawn to the screen (so it can float over other windows, without stealing the focus of them)...
3.2 Or Qt doesn't grab the right parent/top window and picks the underlaying desktop...
3.3 Or the getGestureWindow/getTopLevelWindow function desn't return the right window...
3.4 -> This all would cause that the wrong window will get the gesture. If we redirect the input we would cause that behaviour too...

4. Other idea: Cinnamons panel draws again the menus simply to the screen. To prevent focus stealing cinnamon orders the new panel-menu "behind" the window/desktop which wrongly gets the input to prevent (again) focus stealing... Qt would grab the wrong window again...

5. Same situation like in 4. But Qt/touchegg gets the wrong window, because its tries to get the toplevel-window by using position data (touch-tap was on XY -> Asking X11 "Which window is at top on XY?"). This occurs because Qt doesn't _knew_ the cinnamon panel-window, but wants to get it (because of the "ALL" filter). If we are not listening to "ALL" windows this would disappear, because we doesn't get the input event (we're listening e.g. only on firefox - not cinnamons panel magic - right?).

I hope you could understand this... It is only a _really_ hypothetical idea why we fail to get the right target window if we're listening to "ALL" on cinnamon... Questions? Or understanding-problems? Ask me!
So, what do you think about it? Point 5 _could_ explain the bug better (because this these includes the "ALL" flag) - but only if 4 is true...

Greetings,
Simonmicro

**Comment by urbie-mk2** [comment]
Does touchegg work in an earlier version ?

**Comment by Simonmicro** [comment]
I don't think so. The problem is that I'm not able to install any older version of touchegg, because it has missing dependencies [for 1.1.0: libutouch-geis1 (>= 2.0.1) but it is not installable] - which I can not resolve. And I can not switch to an older version of my distribution because of problems with older installer (Ubiquity) versions of Linux Mint (my distro) on my tablet. Beside the fact I would loose all my data ;)

Maybe a docker image _could_ help.

Thanks,
Simonmicro

**Comment by urbie-mk2** [comment]
Try earlier versions of xf86-input-synaptics. I set up touchegg in 2015 and it is still working now after 3 years of updates (arch linux) and synaptics is the only package I do not upgrade.

**Comment by Simonmicro** [comment]
According to the package description this driver is meant for _touchpads_ but I'm experiencing this touchegǵ-problems on my tablet with a _touchscreen_. Additionally this package is not even installed on my system (and has on the ubuntu-tree an other name). Are you shure I should try to install, configure and downgrade this package?
Simonmicro

**Comment by urbie-mk2** [comment]
Which driver is used? Libinput?

**Comment by Simonmicro** [comment]
The touchscreen inside my tablat seems to be an "Goodix Touchscreen device" - so its kernel module is used: goodix
~modinfo goodix~
filename:       /lib/modules/4.19.0-rc5+pwm-fix/kernel/drivers/input/touchscreen/goodix.ko
license:        GPL v2
description:    Goodix touchscreen driver
author:         Bastien Nocera <hadess@hadess.net>
author:         Benjamin Tissoires <benjamin.tissoires@gmail.com>
srcversion:     BA08C10B4BAF0E8784AAD02
alias:          i2c:GDIX1001:00
alias:          acpi*:GDIX1002:*
alias:          acpi*:GDIX1001:*
depends:        
retpoline:      Y
intree:         Y
name:           goodix
vermagic:       4.19.0-rc5+pwm-fix SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4

I don't know: Is this that what you asked for?
Simonmicro

**Comment by urbie-mk2** [comment]
Ok, can you check which X11 driver is being used ? mostly called xf86-input-* and can be found in the x11 log or system log

**Comment by Simonmicro** [comment]
Seems like libinput is used. This is some piece of the Xorg.0.log:
`[    12.982] (II) config/udev: Adding input device Goodix Capacitive TouchScreen (/dev/input/event2)
[    12.982] (**) Goodix Capacitive TouchScreen: Applying InputClass "libinput keyboard catchall"
[    12.982] (**) Goodix Capacitive TouchScreen: Applying InputClass "libinput touchscreen catchall"
[    12.982] (II) Using input driver 'libinput' for 'Goodix Capacitive TouchScreen'
[    12.982] (**) Goodix Capacitive TouchScreen: always reports core events
[    12.982] (**) Option "Device" "/dev/input/event2"
[    12.982] (**) Option "_source" "server/udev"
[    12.983] (II) event2  - Goodix Capacitive TouchScreen: is tagged by udev as: Keyboard Touchscreen
[    12.983] (II) event2  - Goodix Capacitive TouchScreen: device is a keyboard
[    12.983] (II) event2  - Goodix Capacitive TouchScreen: device is a touch device
[    12.983] (II) event2  - Goodix Capacitive TouchScreen: device removed
[    13.019] (II) libinput: Goodix Capacitive TouchScreen: needs a virtual subdevice
[    13.019] (**) Option "config_info" "udev:/sys/devices/pci0000:00/808622C1:01/i2c-1/i2c-GDIX1001:00/input/input2/event2"
[    13.019] (II) XINPUT: Adding extended input device "Goodix Capacitive TouchScreen" (type: TOUCHSCREEN, id 8)
[    13.019] (**) Option "AccelerationScheme" "none"
[    13.019] (**) Goodix Capacitive TouchScreen: (accel) selected scheme none/0
[    13.019] (**) Goodix Capacitive TouchScreen: (accel) acceleration factor: 2.000
[    13.019] (**) Goodix Capacitive TouchScreen: (accel) acceleration threshold: 4
[    13.020] (II) event2  - Goodix Capacitive TouchScreen: is tagged by udev as: Keyboard Touchscreen
[    13.021] (II) event2  - Goodix Capacitive TouchScreen: device is a keyboard
[    13.021] (II) event2  - Goodix Capacitive TouchScreen: device is a touch device
[    13.022] (II) config/udev: Adding input device Goodix Capacitive TouchScreen (/dev/input/mouse0)`
and
`[    13.127] (**) Goodix Capacitive TouchScreen: Applying InputClass "libinput keyboard catchall"
[    13.127] (**) Goodix Capacitive TouchScreen: Applying InputClass "libinput touchscreen catchall"
[    13.127] (II) Using input driver 'libinput' for 'Goodix Capacitive TouchScreen'
[    13.127] (**) Goodix Capacitive TouchScreen: always reports core events
[    13.127] (**) Option "Device" "/dev/input/event2"
[    13.127] (**) Option "_source" "_driver/libinput"
[    13.127] (II) libinput: Goodix Capacitive TouchScreen: is a virtual subdevice
[    13.127] (**) Option "config_info" "udev:/sys/devices/pci0000:00/808622C1:01/i2c-1/i2c-GDIX1001:00/input/input2/event2"
[    13.128] (II) XINPUT: Adding extended input device "Goodix Capacitive TouchScreen" (type: KEYBOARD, id 12)`

I think, thats it. :grin: 
Simonmicro

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
