### ISSUE TITLE
Spread all windows

### ISSUE THREAD

**Issue by zachkont** [JoseExposito/touchegg#293]
I have a gesture set to send_keys Super+W  which in ubuntu spreads all windows, and it works great except that after they have been spread, using it again only sends super (which opens the search launcher). Using super+W when spread does not.

**Comment by urbie-mk2** [comment]
can you verify that this actually happens (2nd time only meta (=super) key is sent) by running touchegg in a terminal window ?

**Comment by zachkont** [comment]
Hmm, turns out this is not the case, the `w` key is sent every time. However the behaviour is not the same as just using the `Super+W` keys to close the spread windows (as mentioned above, the search launcher opens with touchegg but not with the keyboard). Perhaps it's a timing thing?

Terminal output is:
```
[+] New gesture: 
	Type      ->  "DRAG" 
	Fingers   ->  5 
	Direction ->  "UP" 
	Action    ->  "SEND_KEYS" 
	App Class ->  "Gnome-terminal" 
	Gesture Start 
	Gesture Update 0 "Drag" 
	Gesture Update 0 "Drag" 
...
	Gesture Update 0 "Drag" 
	Gesture Finish 
```

**Comment by urbie-mk2** [comment]
Ok, since I use KDE and not ubuntu, I use the key combiniation Super+Q to show the activity sidebar in order to test this issue. 

If the gesture with action 'send keys' did not work it would open the kde menu instead. This did not happen in my test. The first gesture opened the sidebar and the second gesture closed it again.

Are other key combinations working for you that include the super key ?

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
