### ISSUE TITLE
Handling one finger tap with touchegg.

### ISSUE THREAD

**Issue by timur-enikeev** [JoseExposito/touchegg#301]
Hello.

Out of the box (without touchegg) all Linux systems that I used handles one finger touch as left mouse button pressing, but some applications don't handle it.

I tried to use touchegg with this part of config:

`                <gesture type="TAP" fingers="1" direction="">
                        <action type="MOUSE_CLICK">BUTTON=1</action>
                </gesture>
`
It works properly for me, but I need to disable left mouse button pressing by system, otherwise I get double clicks when I tap screen.

Can I do it?

**Comment by JoseExposito** [comment]
A possible solution could be to send the tap only to the apps you are
having issues to recognise the default system click, i.e., move the
configuration you copy and paste here from the "all' scope to the app
specified scope.

El 2 abr. 2017 7:12 p. m., "timur-enikeev" <notifications@github.com>
escribió:

Hello.

Out of the box (without touchegg) all Linux systems that I used handles one
finger touch as left mouse button pressing, but some applications don't
handle it.

I tried to use touchegg with this part of config:

<gesture type="TAP" fingers="1" direction=""> <action
type="MOUSE_CLICK">BUTTON=1</action> </gesture>
It works properly for me, but I need to disable left mouse button pressing
by system, otherwise I get double clicks when I tap screen.

Can I do it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JoseExposito/touchegg/issues/301>, or mute the thread

**Comment by timur-enikeev** [comment]
>A possible solution could be to send the tap only to the apps you are having issues to recognise the default system click, i.e., move the configuration you copy and paste here from the "all' scope to the app specified scope.

These applications don't recognize touching only in some regions of window. E.g. audacity doesn't recognize touch only on buttons "play", "stop", "pause".

Does anybody know how to prevent system from sending touches to applications except touchegg?

**Comment by urbie-mk2** [comment]
Hi, Can you explan first what you want to achieve ? the gesture you gave 
```<gesture type="TAP" fingers="1" direction=""> <action type="MOUSE_CLICK">BUTTON=1</action> </gesture>``` can be done withouch touchegg.

**Comment by timur-enikeev** [comment]
>Hi, Can you explan first what you want to achieve ? the gesture you gave
<gesture type="TAP" fingers="1" direction=""> <action type="MOUSE_CLICK">BUTTON=1</action> </gesture> can be done withouch touchegg.

I said that it doesn't work (or doesn't work properly) in some applications, as example Goldendict and audacity.

**Comment by urbie-mk2** [comment]
Ok, so is the assumption correct in that you try to make the single tap touch gesture work only for specific applications or windows and want tap touch to not work for selected applications or windows only ? Otherwise I would wonder why a gesture configured by touchegg is required at all since the default functionality provided by the touchpad drivers already achieve that purpose.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your bug report. Please, let me know if you have any problems with the new version.
