### ISSUE TITLE
Apple Magic Trackpad

### ISSUE THREAD

**Issue by anton-johansson** [JoseExposito/touchegg#309]
Hey! Interesting project. I'm planning on buying an Apple Magic Trackpad to try out for my Ubuntu installation. However, I'm curious if anyone has any experience with it, together with `touchegg`? For example, is there any (or planned) support for the force touch? Is the force touch data even available when running on a Linux distribution (I've read that it's hard to get this kind of data when not on a Mac)?

Any information appreciated!

**Comment by urbie-mk2** [comment]
force touch needs to be supported in the driver and by the layers above (by libinput) and by the end user software as well (e.g. chrome or gesture tool like touchegg) all of which does not seem under intense development to implement force touch.
Touchegg relies on GEIS to get gestures and processes these..
Force touch could happen, when I dont know, but then I am sure it will happen with libinput. Since touchegg and GEIS are not compatible with libinput at this time you could follow the development of libinput-gestures to see when support arrives.
