### ISSUE TITLE
i can't install touchegg on feodra 27

### ISSUE THREAD

**Issue by wotmshuaisi** [JoseExposito/touchegg#322]
rpm repo: https://copr-be.cloud.fedoraproject.org/results/mhoeher/multitouch/fedora-26-x86_64/

what can i do?? help

**Comment by mhoeher** [comment]
Hi @wotmshuaisi,

I am the owner of the mentioned repository. Although Touchegg is still contained in the repository, it is not really maintained right now. As an alternative, you can try to install `libinput-gestures` from the same repository. See [this comment](https://www.rpdev.net/wordpress/martin/2014/08/03/mac-os-like-gestures-on-linux/#comment-874) for detailed information.

If using `libinput-gestures` is not an option, please let me know, getting the Touchegg RPMs installable again should be possible; however, note that due to Fedora changed to `libinput` for input device handling, Touchegg might anyway no longer work (at least out of the box).

**Comment by wotmshuaisi** [comment]
@mhoeher 
hello,
i installed  libinput-gestures-2.29-1.fc26.x86_64, and run `libinput-gesture -c /etc/libinput-gesutre.conf`, it works very well, but i got a big problem!
my pointer became not fluent, before i login, my pointer was well, but after i login to my desktop, my pointer became very not fluent, so i `dnf remove libinput-gestures` but nothing useful, even i reboot my system.
now what can i do?
help!

**Comment by mhoeher** [comment]
Did you ran any other commands except the one you listed above? If you installed the package according to the instructions given in the comment I mentioned, doing a simple uninstall should definitely do the trick.

In particular, did you run `sudo libinput-gestures-setup install` as mentioned in the project's README? I hope not, because the RPM does exactly this for you. If you did, you can try to run `sudo libinput-gestures-setup uninstall`.

Did you try to add your user to the `input` group? Again, this as well should not be done when using the RPM (which uses a wrapper to avoid you having yourself to add to that group).

If nothing of this applies, please consider raising either an issue against [libinput-gestures](https://github.com/bulletmark/libinput-gestures) if you think the issue is related to the script itself or against [my packaging project](https://gitlab.com/rpdev/fedora-multitouch) if you think it is rather about the packaging and continue the discussion there, so we don't have to clutter this project's bug tracker ;-)

**Comment by wotmshuaisi** [comment]
@mhoeher guess what? i delete ~/.config/dconf/user, it fixed!
