### ISSUE TITLE
Directions for CHANGE_DESKTOP Up/Down/Left/Right

### ISSUE THREAD

**Issue by ska2342** [JoseExposito/touchegg#338]
Over the weekend and I looked into providing a PR that would allow to give `direction` "up", "down", "left", "right" similar to how "next" and "previous" work currently in the CHANGE_DESKTOP action.

But I stumbled over all the flexibility that the EWMH `_NET_DESKTOP_LAYOUT` allows.

Would you be happy to receive a PR that only deals with one orientation and one starting corner and be tested on KDE?

**Comment by JoseExposito** [comment]
Hi @ska2342 ,

First of all, thank you very much for your work!

Indeed `_NET_DESKTOP_LAYOUT` is powerful. I already had a look into it, but I discarded the idea because, in my opinion, having just previous/next provides a better user experience, let me explain it:

Having gestures to navigate to the desktop placed up/down/left/right will force you reserve 4 different gestures just for desktop navigation, lets say 4 fingers swipes. That doesn't leave you room to use other actions like showing the desktop (this is specially useful in KDE, to easily check your plasmoids) or presenting windows. However, with just previous/next you have more room for more gestures and you can easily navigate through your desktops.

However, I'll leave this issue open and if it receives enough :+1: reactions I'll implement this feature for 2.0.1.

I guess being able to use previous/next in addition to up/down/left/right will fit both user cases :smile:

**Comment by ska2342** [comment]
I humbly disagree here. Living on a 3x3 grid of desktops since 1995, "next" and "previous" don't make sense to me at all. I never think of my desktops as a linked list or a row or anything else 1d. I wouldn't mind having to use 4 gestures for this. (Personally, I'd likely go with 3 finger swipes in the different directions.) 

Unfortunately, I have no idea in which way other window managers chose to set the desktop layout. KDE Plasma just sets the number of rows and let's you figure out the columns yourself from the total number of desktops. They have a horizontal orientation and the starting corner is top left. 

Also, boy is my C++ rusty! ;-)

**Comment by JoseExposito** [comment]
Fair enough, I'll try my best and add support for it in a future release 😄

**Comment by ska2342** [comment]
I can try this, too. But please be aware that it's been ca 15 years since I last coded in C++.

**Comment by JoseExposito** [comment]
Hi @ska2342 

I just added support for up/down/left/right in CHANGE_DESKTOP :smile: 

In case you want to try it, you can compile the latest source code, or wait for the 2.0.3 release.

Jose

**Comment by ska2342** [comment]
Cool! I set the 3 finger swipe to desktop switching up/down/left/right and it seems to work fine. Personally, I'm super happy that it doesn't scroll when hitting an edge. I can imagine that there will be people who disagree. ;-)

FWIW: KDE Plasma on Kubuntu 20.04 with 3x3 desktops.

**Comment by amerkay** [comment]
Hi,
I love this. Great work!

I'm trying to setup the the up/down/left/right CHANGE_DESKTOP on KDE and I can't seem to get it working. I see the animation arrows, but the desktop does not switch.

Is it using a certain key-shortcut? I use CTRL+ALT+arrows to switch between my 2x2 desktops.

I'm running KDE Plasma 5.20.4 on Manjaro Linux. Here is part of the config:

```xml
<gesture type="SWIPE" fingers="4" direction="UP">
  <action type="CHANGE_DESKTOP">
    <direction>down</direction>
    <animate>true</animate>
    <animationPosition>down</animationPosition>
  </action>
</gesture>
…
```

Thanks :)
