### ISSUE TITLE
[Feature Request] Add a GUI for configuration

### ISSUE THREAD

**Issue by matfantinel** [JoseExposito/touchegg#340]
First of all, congrats on the 2.0 release! It's really awesome and I'm already using and loving it.

This is more of an epic that could be built on a separate repository, but we can centralize the discussion on this issue for now.

To make Touchégg even more user-friendly and accessible to everyone, we could build a GUI to allow changing the configuration. It could also automatically add itself to startup.

**Comment by matfantinel** [comment]
elementaryOS has some great guidelines and starting templates for building this. Me and a lot of other devs have already some experience developing apps on it and releasing them on AppCenter/Flathub.

As far as I know, the codebase of the GUI app would be quite simple. It would just have to add itself to startup, and control the contents of the .conf file, which is not hard to do at least with Vala.

Having touchpad gestures easily installable through the AppCenter/GNOME Software/whatever would be awesome!

**Comment by JoseExposito** [comment]
Thanks for your feedback, I'm glad you find it useful :smile: 

This is definitely something that is in my ToDo list. There was a Qt 4 based GUI for the previous versions (there is a video on my YouTube channel in case you are curious) but it needs so many updates that I plan to port it to Gtk.

Not so sure about Vala, since I have no experience with it. C++ is just too slow (at development time) and the performance boost is not required. So I was thinking about JavaScript, I need to test gjs on elementary OS and KDE before I choose that path.

I already have some ideas about the design and of course contributions and help publishing are welcome.

**Comment by matfantinel** [comment]
I mentioned Vala because it has a fair amount of apps we can borrow code/ideas from (and I also have some experience with it). I think a GTK interface would be the best option, since it's well supported everywhere (while GNOME/elementary don't always play well with Qt).

I'd volunteer for building a prototype, but unfortunately my free time is well... not free anymore, as I'm working on a different project. But there are some developers on the elementary Community Slack which may be really excited to help. I can post about it there if you'd like ;)

**Comment by JoseExposito** [comment]
This is finally ready!
https://github.com/JoseExposito/touche

It is available on Flathub and as a deb package :smile:
