### ISSUE TITLE
Keep text from getting highlighted/objects from getting selected by multi touch input

### ISSUE THREAD

**Issue by coldspark29** [JoseExposito/touchegg#401]
### Is your feature request related to a problem? Please describe

It is annoying that in KDE text is getting highlighted in editors or in dolphin the obects are being selected when you are using gestures. I already filed a bug in [kwin](https://bugs.kde.org/show_bug.cgi?id=430109). I am not sure where the right place for this is. I am guessing though that you are aware of this issue and would have fixed it, if it was possible from touchegg.

### Describe the solution you'd like

Ignoring highlighting and object selection on multitouch input. This way it would not interfere with touchegg.

### Describe alternatives you've considered

I would like KDE to be more touch friendly in the first place, but that is another story.

**Comment by JoseExposito** [comment]
Is this happening when you perform gestures on your touchpad or touchscreen?

I noticed this issue is present on touchscreens, but it is not an issue with Touchégg, it is the default behaviour. My understanding is that this is an issue with `libinput`. Well, not really an issue, but as far as I know, there is no way to tell `libinput` that Touchégg is handling the gesture and stopping the default action to be triggered.

**Comment by JoseExposito** [comment]
just saw your report on libinput, let's see what Peter Hutterer has to say, if there is anyone who knows the answer it is him:
https://gitlab.freedesktop.org/libinput/libinput/-/issues/546

**Comment by JoseExposito** [comment]
Closing this issue as discussed in libinput's bug tracker. 
I'm sorry I can not solve this on my side.
