### ISSUE TITLE
Animated gestures not working on KDE Plasma 5.18+, Qt 5.12+

### ISSUE THREAD

**Issue by KorraHarraway** [JoseExposito/touchegg#407]
### Describe the bug

Animate gestures like maximizing previously minimized window and tiling are not working and crash the touchegg application (although the daemon remains).
The gestures are being recognized (see Workaround below), so I can still assign them to other functions.

The gestures for Window Minimization and Window Closing are working out of the box. 

### Your environment

 * Version of Touchégg: 2.0.4 Run
 * Operating System: openSUSE Leap or Tumbleweed
 * Desktop Environment: KDE Plasma 5.18+, Qt 5.12+

### Workaround:

I have modified touchegg.conf and assigned the desired functionalities to KDE keyboard hotkeys (`<action type="SEND_KEYS">`) or to run command (`<action type="RUN_COMMAND">`) accordingly.

**Comment by JoseExposito** [comment]
Are your panel(s) configured to auto-hide? It might be a similar issue to https://github.com/JoseExposito/touchegg/issues/381

**Comment by siddhantladdha** [comment]
Hi, I am using 
- Version of Touchégg: 2.0.4
- Operating System: Arch Linux
- Desktop Environment: KDE Plasma 5.20.4, Qt 5.15.2

Both the top and bottom panels on my DE are set to autohide. I am not experiencing any crashes as mentioned in #381 

Do you need any help in testing it out? Share your configuration so that I can reproduce the issue.
Thanks

**Comment by JoseExposito** [comment]
Closing it as it has been inactive for 2 weeks, feel free to reopen it with more information.
