### ISSUE TITLE
Touchscreen long press and hold as a new gesture (e.g., right mouse click)

### ISSUE THREAD

**Issue by KorraHarraway** [JoseExposito/touchegg#408]
### Describe the solution you'd like

The current behavior if you tap and hold pressing the touchscreen is to active the drag functionality.
It would be nicer that, if you keep long pressing even further the touchscreen, it activates a gesture. For example, it could trigger the right mouse click.

Inconsistencies with the native drag functionality (that usually comes with Desktop Environments) can be mitigated by letting the user edit the touchegg.conf file in order to set a threshold (in seconds) for the time the touchscreen needs to be hold-pressed after which the gesture would be recognized.

### Describe alternatives you've considered

Right now I have been using the right mouse click assigned to the 2 finger tap. But the behavior is very inconsistent because it is very hard to determine 100% of the time which of the two fingers would be the one below which the action (in the case, clicking) will be triggered.

**Comment by JoseExposito** [comment]
I experimented with this gesture, but I ended up discharging the idea because it was very uncomfortable not being able to rest your hand in the touchscreen in a tablet-like device.

Also, it interferes with the swipe and pinch gestures if you take too long to start the movement.

In addition, some apps start a drag action once you press with a finger and, if the right click action is triggered once the drag started, the contextual menu might be different.

In general, I wasn't able to build something that felt nice for many reasons, so I decided to drop the idea.

Have you tried to request this feature on the apps you are using? I believe this is the way to go.
