### ISSUE TITLE
Work with sway

### ISSUE THREAD

**Issue by toger5** [JoseExposito/touchegg#416]
### Is your feature request related to a problem? Please describe
The gestures have no effect on a sway compsitor.

### Describe the solution you'd like
I would like the prodefined gestures to work on sway.

### Describe alternatives you've considered

If it works on sway and it is just additional work to setup it would be great to have some information in the readme.

**Comment by JoseExposito** [comment]
Hi! 

Touchégg is X11 only. Unfortunately, porting it to Wayland is not possible because only the compositor has access to gestures plus, unlike in X11, there is not a protocol to change window sizes.

If you want gestures on Sway, you'll need to request them in their project, maybe the devs are open to implement it.

**Comment by toger5** [comment]
Libinput-gesture does work. That is what i use atm to setup gestures. Touchegg looks nicer to configure.

**Comment by JoseExposito** [comment]
No, it is not possible for me to display animations on Wayland because I don't have access to screen size that is not covered by panels. If I animate full screen it just looks bad.

However, you can use the run command action:
https://github.com/JoseExposito/touchegg#execute-a-command-run_command

And use Sway specific commands (swaymsg?) or xdtools to perform shortcuts.
I guess that's how libinput-gestures works.

**Comment by toger5** [comment]
There are the additional overlayed animations. 
particularly this one:
![image](https://user-images.githubusercontent.com/16718859/103896547-70d13a80-50f2-11eb-862d-a60f6b492eb5.png)
which would be super interesting to have in sway as well. I think the protocol which is used for the waybar for example woul allow to overlay the arrow on top of the screen on the left/right side.

That would be amazing to have. A visual feedback before the run command to change workspace is executed.
