### ISSUE TITLE
Reverse gesture to cancel the previous one

### ISSUE THREAD

**Issue by mateMathieu** [JoseExposito/touchegg#417]
### Describe the bug

When we pinch sometimes, it registers as swipe. This is expected behavior as these gestures are not perfect and sometimes they are not done well or in proper wrist-to-finger position.
We are also sometimes messing up between the different gestures actions.

But these gestures have a reversal effect. Pinch in and out are reverse, left and right are also reverse. That I why we should have a reverse gesture if we did not operate the gesture the way we intended intentionally (or not actually).

### Expected behaviour

When I swipe three fingers up to maximize the window, if in the following seconds I swipe tree fingers down, the expected behavior should be to cancel the maximization of the window and go back to the original window size.

### Actual behaviour

When I swipe up the window maximizes, then when I swipe down, it minimizes it.

### Your environment

Version of Touchégg: 2.0.0
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-58-generic

**Comment by mateMathieu** [comment]
And thank you so much for making this high quality software. That will seriously boost linux popularity.
Good job! Regards

**Comment by JoseExposito** [comment]
Hi! Thanks :D

It is actually possible to cancel a gesture. For example, if you start swiping up with 3 fingers to maximize a window and you change your mind, instead of completing the gesture, swipe down without raising your fingers and the window will not be maximized.

You are showing this behaviour because you configured 3 finger swipe down to minimize windows.

If you really want to be able to maximize/restore window swiping up and down, you can use this config, but you won't be able to minimize swiping down of course:

```xml
<gesture type="SWIPE" fingers="3" direction="UP">
  <action type="MAXIMIZE_RESTORE_WINDOW">
    <animate>true</animate>
  </action>
</gesture>
<gesture type="SWIPE" fingers="3" direction="DOWN">
  <action type="MAXIMIZE_RESTORE_WINDOW">
    <animate>true</animate>
  </action>
</gesture>
```

About pinch, yes, it is not reliable
