### ISSUE TITLE
Feature request: multiple actions per gesture

### ISSUE THREAD

**Issue by F0xedb** [JoseExposito/touchegg#418]
Currently it seems `touchegg` only allows one `<action></action>` element in `<gestures></gestures>`

It would be nice if touchegg had support for the following syntax:
```xml
<gesture type="SWIPE" fingers="3" direction="LEFT">
   <action type="RUN_COMMAND">
        <repeat>false</repeat>
        <command>notify-send 'Hello' 'World'</command>
        <on>begin</on>
  </action>
  <action type="CHANGE_DESKTOP">
    <direction>auto</direction>
    <animate>true</animate>
    <animationPosition>auto</animationPosition>
  </action>
</gesture>
```

The expected behavior for me would be to run the command when starting the gesture and performing the `CHANGE_DESKTOP` action in parallel to the command.

I hope this can make it to the next release 🙂

**Comment by JoseExposito** [comment]
What's your real world use case for this?

**Comment by F0xedb** [comment]
I'm using awesomewm which has multiple workspaces in a single desktop (called tags)
The changing of tags is not supported by the `CHANGE_DESKTOP` action type.

I can run a shell script to change between tags but then I lose the nice animation provided by the `CHANGE_DESKTOP` action.
My idea was to combine both actions to achieve the effect.

An alternative would be to allow animations on commands?
Or maybe you have a better solution?

Thanks for replying so fast!!

**Comment by JoseExposito** [comment]
Ok, so the problem is that AwesomeWM doesn't support `_NET_CURRENT_DESKTOP`, maybe you could try to request from them to support it. For reference, it is part of this spec:
https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45760170877056

I don't want to make the configuration more difficult just to add support for one feature of a WM, sorry.
You can always use the SEND_KEYS action to switch between your desktops. Have a look to the Alt+Tab example, you can modify it so you can change between multiple desktops with one gesture:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

**Comment by iamkroot** [comment]
> What's your real world use case for this?

A bit late, but having multiple actions would allow for the scheme described in #403 (defining multiple actions, with first action having a `noExecute` flag, second being the `SEND_KEYS`). This would effectively solve #345. Having the config support multiple actions will be transparent to the end user (by virtue of XML), unless they need it.
