### ISSUE TITLE
Timestamping and verbosity of the log

### ISSUE THREAD

**Issue by Desiderius77** [JoseExposito/touchegg#431]
The log of the client is very helpful for debugging. But it produces a lot of information which is not very easy to explore afterwards.

1) It would be very interesting to be able to manage the level of verbosity of the client to have more or less massages for example to have only the gesture which has been detected and not the detailed percentage of the gesture 

2) To be able to archive logs of different sessions of touchegg, it would be nice to have the date and hour of the log inside the log itself possibly only at the beginning of the file 

In any case, thanks a lot to Jose for this marvelous software

**Comment by JoseExposito** [comment]
Thanks for your feature request, there is a lot of room for improvement here. I'll do my best as soon as I have some time :D

**Comment by imabuddha** [comment]
@JoseExposito When you do get the time I'd really like to be able to have the option to turn off the logging of normal gesture messages. They are very handy during setup, but no need for them in normal use. 🙇

**Comment by imabuddha** [comment]
@JoseExposito I just looked through the source code, and I think it wouldn't be too difficult to add some verbosity options to the client cmd line. I might have some free time to do this but I have questions:

1. Would you prefer the verbosity option to be passed to `daemonClient.run();` or as a param to the `DaemonClient` constructor?
2. What option name(s) would you prefer? I could imagine either a short form like `-v0` for no gesture msgs, `-v1` for gesture but no % msgs (as @Desiderius77 asked for in his point 1). Another possibility is longer forms like `--no-messages`, `--no-percent-messages`.
3. I think that at least for the initial implementation I'd keep it simple: no date/time added & only for client mode. So for example, the user could run like this: `touchegg --client --no-messages` for no gesture messages.

Any feedback or guidance would be appreciated. 🙇

**Comment by JoseExposito** [comment]
Hi @imabuddha 

I was thinking about creating a singleton and using it in the whole app.
The logger singleton should have different log level methods (error, warning, info, debug) and overload the << operator, like std::cout.
I'll log error, warning and info by default and debug only with a verbose flag.
A decent args parser it's required as well.

I'll like to review every message and add an remove some of them. Contributions are welcome, but this is not a quick one, so up to you.

**Comment by imabuddha** [comment]
@JoseExposito, ah, you have a much more ambitious concept in mind! 

I think your idea is the right way to do it for the long term. The timing is funny because I was just about to start on the changes to the main.cpp file. I did fix a typo already on line 45 ("transforms").

It's probably been 20 years since I did any c++, so the changes you propose might take me a while. Maybe it's a good opportunity to revisit old times. 😉

### Logger class files location
So the logger singleton class files should go under `touchegg/utils`, right?

I'm old-school, so even back in my c++ days I didn't use operator overloading much. I'll take a look at the language docs to refresh my memory.

### In usage you'd like something like the following, right?

``` cpp
  log.info << "Touchégg " << VERSION << "." << std::endl;

  log.error << "Wallet empty!" << std::endl;

  // etc…
```

### What about the command line options?
According to [this](https://tldp.org/LDP/abs/html/standard-options.html) --quiet or -q should suppress all msgs, --verbose or -v should show all (incl. debug), but we'd need more flags if finer control is desired. For my personal use case I'd like to suppress the all of the gesture msgs (no warnings about unconfigured action, etc.), and apparently @Desiderius77 would like a way to suppress the gesture update msgs, which would be a subset of info.

#### How about these?
_no flags_ = show error, warning, info
**--verbose** | **-v** = show all (incl. debug)
**--quiet** | **-q** = suppress all msgs
**--no-gesture-messages** = no gesture msgs (my use case)
**--no-update-messages** = no  gesture update msgs (for @Desiderius77)

Either of the last 2 flags could also be used with verbose.

### Args parser
The current arg code in main.cpp is a bit simplistic. 😸 Did you have a particular _args lib/module/example func_ in mind, or would it be OK to keep it simple but improve it enough to support these flags?

### Date-time
I'm inclined to add this only to the client/server startup msgs, and perhaps errors. (in this format: `[2021-01-24T10:53:56.818Z]`)

**Comment by imabuddha** [comment]
@JoseExposito I'm working on the args parsing now, and the main issue is the optional thresholds for daemonMode. I'm trying to maintain compatibility with current behavior of touchegg in all ways, however since the thresholds are just numbers it's a PITA. I see 2 possibilities:
1. Keep the optional thresholds just as they are, 2 optional numbers immediately following `--daemon`. This would mean that any log flags must appear before `--daemon`.
2. Add new flags for the thresholds like: `start-threshold=X finish-threshold=Y`. This would allow any flag order.

## Which do you prefer?

I think the PR should be ready in a day or two.

**Comment by imabuddha** [comment]
@JoseExposito OK, it's done. PR incoming!

* I reviewed the prj src files quickly & changed all of the msgs that went to std::cout to now go to the Logger.
* I implemented everything as described in yesterday's comment.
* I tested all of the options on my machine, but of course it need to be more thoroughly reviewed & tested.

🙇

**Comment by JoseExposito** [comment]
Hi @imabuddha 

Thanks a lot for your pull request!! I'll do my best to answer your questions, even though your approach is reasonable.

> So the logger singleton class files should go under touchegg/utils, right?

Yes, `utils` is a good place for both the logger class and the command line argument parser.

> How about these?

I only have doubts about `-v`. It is usually equivalent to `--version` so maybe we could use `--debug` instead?
In this case only warning and error messages are displayed by default and the `--debug` / `-d` flag enables logging for every other message (info & debug).

> In usage you'd like something like the following, right?
> log.info << "Touchégg " << VERSION << "." << std::endl;
> log.error << "Wallet empty!" << std::endl;

That syntax is the dream :smile: 

> --no-gesture-messages = no gesture msgs (my use case)
> --no-update-messages = no gesture update msgs (for @Desiderius77)

I'm fine removing those and just using info/debug log levels. It'll keep everything simpler.

> I'm inclined to add this only to the client/server startup msgs, and perhaps errors. (in this format: [2021-01-24T10:53:56.818Z])

I'm fine including it everywhere. I'll make the code simpler and also, because most messages will be only displayed and could be useful for troubleshooting with the debug flag.

> I'm working on the args parsing now, and the main issue is the optional thresholds for daemonMode. I'm trying to maintain compatibility with current behavior of touchegg in all ways, however since the thresholds are just numbers it's a PITA.

I think you managed to solve this problem already, but if it is too difficult, just use the easiest approach.

**Comment by imabuddha** [comment]
> I only have doubts about `-v`. It is usually equivalent to `--version` so maybe we could use `--debug` instead?
> In this case only warning and error messages are displayed by default and the `--debug` / `-d` flag enables logging for every other message (info & debug).

Sounds good!

> > In usage you'd like something like the following, right?
> > log.info << "Touchégg " << VERSION << "." << std::endl;
> > log.error << "Wallet empty!" << std::endl;
> 
> That syntax is the dream 

Sometimes dreams come true.

> > --no-gesture-messages = no gesture msgs (my use case)
> > --no-update-messages = no gesture update msgs (for @Desiderius77)
> 
> I'm fine removing those and just using info/debug log levels. It'll keep everything simpler.

Excellent!

> > I'm inclined to add this only to the client/server startup msgs, and perhaps errors. (in this format: [2021-01-24T10:53:56.818Z])
> 
> I'm fine including it everywhere. I'll make the code simpler and also, because most messages will be only displayed and could be useful for troubleshooting with the debug flag.

I'm not sure about this. For example, even in `-debug` you probably don't need to see this for every gesture update % msg do you? For now I'll leave it as-is. You can change it later or just include the date/time code (presumably in a new helper func) in the msgs where you really want it.

**Comment by JoseExposito** [comment]
Thanks a lot for your work @imabuddha, this will be included in the next release :smile:

**Comment by imabuddha** [comment]
@JoseExposito Thank you for including this PR, and taking care of the final minor changes that I didn't have time to do.

However, it seems that you changed the default logging such that info msgs are displayed, **which means that all of the gesture msgs will be displayed which is exactly what I wanted to avoid clogging up my log files**. Of course I could use the quiet flag, but that would also prevent seeing warnings & errors! 😱

Please consider reclassifying the gesture msgs to be debug, or at the very least adding back the no-gesture-messages option.

**Comment by JoseExposito** [comment]
Ups, yes, I forgot to set those messages as debug, fixed!
