### ISSUE TITLE
SEND_KEYS ignores action_execute_threshold

### ISSUE THREAD

**Issue by manjaronoob** [JoseExposito/touchegg#433]
### Describe the bug

I'm not sure if this is an issue with the software or some undocumented functionality.

Using the example config Pinch to zoom uses <action type="SEND_KEYS"> under <application name="All">.

Even though <property name="action_execute_threshold">20</property> is set under settings, the first keystroke sent by SEND_KEYS is sent at 10%, and repeated every 10%. Even when changing <property name="action_execute_threshold">5</property> or <property name="action_execute_threshold">50</property> the keystrokes are sent at 10% then repeated every 10%. (Other action types are affected by the changed threshold.)
It is a good thing that SEND_KEYS uses a different threshold than the other action types. However there should be a way to set the threshold for this action individually for each gesture definition. Also a way to set the repeat interval individually for each SEND_KEYS gesture would be nice.

### Expected behaviour

SEND_KEYS action reflects the setting action_execute_threshold
OR
Documentation tells how to set the action_execute_threshold for SEND_KEYS action.

### Actual behaviour

SEND_KEYS executes at 10%, no matter the value of action_execute_threshold 

### Your environment

 * Version of Touchégg: 2.0.5
 * Operating System: Manjaro
 * Desktop Environment: Xfce

**Comment by JoseExposito** [comment]
Hi! The send keys action has 2 modes. Repeat (the behaviour you described) and not repeat, as documented here:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

If you just want to execute a single shortcut, set `repeat` to `false `.

The `action_execute_threshold` as in the docs is the "percentage of the gesture to be completed to apply the action" and it is not related to the amount of steps executed by `SEND_KEYS`.

That 10% that you mentioned is not configurable and I don't plan to make it configurable because, the config file is already pretty complex and because other values make it difficult to use.

Anyway, do you have any issue with the default behaviour? How many steps would you like to have?

**Comment by manjaronoob** [comment]
Thanks Jose.
Yes, the feel of pinch to zoom is kind of weird. Maybe because my touchpad is large and my fingers aren't as flexible as others. If I use two fingers on one hand to pinch out I have to stretch my finger muscles before something happens. So basically the pinch action becomes a two hand action. 
I've seen config files being way more complex than touchegg. I'd say the touchegg config is fairly simple - there's only 4 settings, 3 gestures and 10 actions available. The config looks complex because these are repeated for each gesture defined but it's really not complex as it mostly is the same thing written several times with minor differences.

I use action_execute_threshold = 5. That makes the gestures behave much like the windows (default) behavior I'm used to. But zoom behaves very differently because the fingers have to move over a very long distance before any action is performed.

**Comment by manjaronoob** [comment]
If there could be two more settings introduced I don't think the config would become significantly more complex.
sendkey_execute_threshold or pinch_execute_threshold (default 10)
sendkey_interval (default 10)

**Comment by JoseExposito** [comment]
It is difficult to make this gesture feel natural for many reasons.

One of them is that pinch, sometimes (this depends on your hardware and you libinput version) is interpreted as a swipe, which can be frustrating.
Also, the browser zoom steps are not linear. Chrome for example goes from 100% to 110%, 125%, 150%... This creates a poor user experience, because you movement is linear.

So, the right place to implement this is in properly Firefox/Chrome, not here. 
Anyways, I don't want to include another couple of variables. They'll also clutter the (work in progress) GUI I'm working on, so I am not implementing this for the moment, sorry.

**Comment by elvisisvan** [comment]
on the topic of pinch to zoom can we make 2-finger pinch zoom the content instead of the page? like zoom into the position of cursor not 80% 90% or 110% 120%, basically like microsoft windows default behavior
