### ISSUE TITLE
Apply action to active window

### ISSUE THREAD

**Issue by squidink7** [JoseExposito/touchegg#435]
I often find I accidentally trigger an action when the mouse is hovering over another application or even the Plasma panel, when I only want to apply the action to the active window.
It would be great if there was a simple toggle in touchegg.conf that let you choose to apply the action to whichever window the mouse is hovering over, or only to the active one.

**Comment by JoseExposito** [comment]
Hi!

Thanks for your feature request. This has been requested [in the past](https://github.com/JoseExposito/touchegg/issues/404) and I decided not to implement it because it requires an extra click to activate the window and, IMHO, that's a worse UX.

In addition it multiplies by 2 the tests I need to do before a release, as I'd need to test everything with the flag enabled and disabled, so for the moment I'm not including it.
