### ISSUE TITLE
Scroll with two fingers

### ISSUE THREAD

**Issue by niccle27** [JoseExposito/touchegg#438]
### Describe the bug

I'm using a lenovo x1 yoga and would like to improve my touchscreen in tablet mode. i wanted to be able to scroll using two fingers.

I couldn't find the proper configuration on the readme, but i was able to generate it using the touchegg-gce software.
This was also found on the arch wiki: 
`<gesture type="DRAG" fingers="2" direction="ALL">
    <action type="SCROLL">SPEED=7:INVERTED=true</action>
</gesture>
`
The scrolling doesn't work tough the event is caught properly.

### Expected behaviour

Scrolling like a mouse but using two fingers on the touchscreen

### Actual behaviour

no scroll available 

### Your environment

 * Version of Touchégg: Touchégg v2.0.5.
 * Operating System: Manjaro
 * Desktop Environment: Xmonad

**Comment by JoseExposito** [comment]
Hi!

I removed the `SCROLL` action in version 2 because the user experience was pretty poor.
It used to emulate scroll sending mouse clicks. The implementation was equivalent to:

```xml
    <gesture type="SWIPE" fingers="2" direction="DOWN">
      <action type="RUN_COMMAND">
        <repeat>true</repeat>
        <command>xdotool click 4</command>
        <decreaseCommand>xdotool click 5</decreaseCommand>
      </action>
    </gesture>
    <gesture type="SWIPE" fingers="2" direction="UP">
      <action type="RUN_COMMAND">
        <repeat>true</repeat>
        <command>xdotool click 5</command>
        <decreaseCommand>xdotool click 4</decreaseCommand>
      </action>
    </gesture>
```

Make sure [xdotool](https://archlinux.org/packages/community/x86_64/xdotool/) is installed in your system.

You will notice that the experience is... :hankey: That's why I removed it.
I'm afraid there is not much I can do here. Touch-screen scroll should be implement by GTK/Qt to get it right.
