### ISSUE TITLE
HOLD gesture

### ISSUE THREAD

**Issue by alexivkin** [JoseExposito/touchegg#450]
Thank you for the awesome tools and for continuing to evolve it. Couldn't do without it on a 7'' RPi touch screen. 

Could you please add HOLD gesture to act on a finger/fingers being held in one position for a preset amount of time? This would make it much easier to gesture on small/portable screens. Most smartphones have this gesture to open menues/actions on an active item. It'd be great to have it tied to the right-mouse button click on Linux.

**Comment by JoseExposito** [comment]
Hi! I experimented with this gesture in the past (see https://github.com/JoseExposito/touchegg/issues/408 and https://github.com/JoseExposito/touchegg/issues/378) but as described in those issues the user experience was poor.

**Comment by alexivkin** [comment]
Not having this function makes touchegg less useful on touchscreens. The two issues you outlined:
* Resting hand on a touchpad: this can be a config options - use touchpad/use touchscreen. Also this can be dealt with palm detection as is done on many touchpads.
* Starting the drag/drag on the initial touch - would this not be a swipe instead of a tap?

**Comment by JoseExposito** [comment]
Hi!

I'm afraid it is not possible to implement palm detection in Touchégg. Such feature should be implemented in a lower level. In libinput, in case you want to investigate about the project.

About the swipe vs hold or tap gesture. Ideally, yes, but I can't stop the application receiving the touch event, so you end up with 2 gestures: Touchégg gesture plus the app gesture.
The hold gesture should be implemented in the toolkit (GTK, Qt...) and handled by apps. Otherwise you end up with double gestures.

I'm sorry I can't give you better news. It is not that I don't think this will be a great feature to have, it's that Touchégg is not the place to implement it.
