### ISSUE TITLE
[BUG] Windows not focused when switching workspaces

### ISSUE THREAD

**Issue by dodalovic** [JoseExposito/touchegg#452]
Hi, thanks for the really nice tool!
One thing I spotted (on my **Pop OS 20.10**) though, is that when I switch workspaces with four fingers up/down swipe, a window that is in the destination workspace is not focused. 

This seems to happen only when one desktop is empty. 

![image](https://user-images.githubusercontent.com/6358061/107327724-df1c6a80-6aad-11eb-8250-f11356f77922.png)

This is my config:

![image](https://user-images.githubusercontent.com/6358061/107327838-1428bd00-6aae-11eb-8999-39538825a217.png)

Thanks once again for the overall really nice experience!

**Comment by JoseExposito** [comment]
Hi!

Thanks for your bug report.

Unfortunately I don't think I can do much to fix it. The way Touchégg changes from one desktop to another is by using an standard message your window manager should support.

Did you noticed if the same happens using a keyboard shortcut? Does it only happens when you switch workspaces from the Activities view? (I'm assuming that is what is happening because of the screenshot).

You can try to change to the next/previous desktop using xdotool (https://unix.stackexchange.com/a/507094) and if it the bug is still present, report it to Pop_OS or GNOME Shell.

Feel free to reopen the issue if you find more useful information, but I believe this is not a bug in Touchégg.

**Comment by dodalovic** [comment]
This configuration works fine:

![image](https://user-images.githubusercontent.com/6358061/107402825-b3789f00-6b04-11eb-9480-258a6de8d6be.png)

**Comment by JoseExposito** [comment]
And?

```
xdotool set_desktop --relative 1
```

```
xdotool set_desktop --relative -1
```

Those command should be doing something similar to what Touchégg does under the hood.
