### ISSUE TITLE
CHANGE_DESKTOP not working in i3wm

### ISSUE THREAD

**Issue by ErikReider** [JoseExposito/touchegg#465]
Doesn't do anything when using i3wm. I can see the animation.

### Your environment

 * Version of Touchégg: v2.0.8
 * Operating System: Manjaro
 * Desktop Environment: i3wm-gaps

**Comment by JoseExposito** [comment]
Touhégg relies on an standard named EWMH. Window managers should implement the properties defined in the standard so tools, like Touchégg, can work across desktops. 

Unfortunately i3 doesn't support the `_NET_CURRENT_DESKTOP` property:
https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm45841377633136
That's why you can not use the switch desktop action on i3.

There is not much I can do to fix this issue, you can report it on i3.
