### ISSUE TITLE
Add more Gestures 

### ISSUE THREAD

**Issue by KonstantMan** [JoseExposito/touchegg#471]
### Is your feature request related to a problem? Please describe
Not really ,I'm just  impressed  from the project and i think it would be nice to have more gestures to configure 
### Describe the solution you'd like
I would like more[ precise gestures](https://www.computerworld.com/article/3014286/windows-10-cheat-sheet.html?page=4) like 3 fingers tap /rotation, swipe from left to right at the bottom or at the top of the trackpad etc.

### Describe alternatives you've considered
I don't really know if other projects like libinput support some of these gestures since for me at least touchegg is the most smooth and easy to configure

**Comment by JoseExposito** [comment]
Hi! Thanks for your feature request.

I wish I could add more gestures, but there are technical limitations that doesn't allow me to do so.

- Tap is only available on touchscreens because I have access to the position of every finger, on touchpads, this is not the case
- Because I don't have access to the absolute position of each finger, I can not implement swipe from the left/right
- Rotate is supported, but I use it to pinch. Pinch recognition can be improved and trying to differentiate a pinch from a rotate ends up with more failed gestures

I wish I could do more, but for the moment, this is what is possible :disappointed:
