### ISSUE TITLE
Declare configuration locations according to xdg base directory specification

### ISSUE THREAD

**Issue by elais** [JoseExposito/touchegg#477]
### Is your feature request related to a problem? Please describe

Currently touchegg searches for its configuration based on the existence of a user's "$HOME/.config/touchegg/touchegg.conf" and a system path based on `SYSTEM_CONFIG_FILE_PATH`.

### Describe the solution you'd like

I would like for touchegg to search for user configuration using `$XDG_CONFIG_HOME/touchegg/touchegg.conf` as opposed to `$HOME/.config/touchegg/touchegg.conf`, only defaulting to the latter directory if `$XDG_CONFIG_HOME` is not defined. I would also like for system configuration to be found by searching first on the path provided by `$XDG_CONFIG_DIRS` and then falling back to `/etc/xdg/touchegg.conf` if none exist. If I'm not mistaken, /usr/share/ or /share is usually one of the default  xdg directories to search. Even still it would likely make more sense for configuration to go under /etc, as that's become the de facto configuration home on linux systems anyways.

### Describe alternatives you've considered

None, but this is a good change.

### Additional context

I use GNU Guix on my desktop and laptop and do not have systemd. Instead I have GNU Shepherd to manage my system services. Rather than adding actual files to paths like /lib, /share, /usr/, or /etc, guix instead symlinks them from the store into these locations just like nix. Having the environment variables handle where to look for configuration makes touchegg more portable as now it won't look in hard coded store paths for configuration and just find it wherever the user or system decides to put it. When creating a fully configurable guix service, it would be helpful if touchegg's installation did not rely on resolving environment variables only at compile time.

I did some mucking around in the code and I don't believe this will be a hard fix. For instance changing `getHomePath` in src/utils/paths.cpp should be as simple as

```c++
std::filesystem::path Paths::getHomePath() {
  // $HOME should be checked first
  const char *homeEnvVar = getenv("XDG_CONFIG_HOME"); // CHANGE THE ENVIRONMENT VARIABE FROM $HOME to $XDG_CONFIG_HOME
  if (homeEnvVar != nullptr) {
    return std::filesystem::path{homeEnvVar};
  }

  // In case $HOME is not set fallback to getpwuid
  const struct passwd *userInfo = getpwuid(getuid());  // NOLINT
  if (userInfo == nullptr) {
    throw std::runtime_error{
        "Error getting your home directory path (getpwuid).\n"
        "Please file a bug report at "
        "https://github.com/JoseExposito/touchegg/issues"};
  }

  const char *workingDir = userInfo->pw_dir;
  if (workingDir == nullptr) {
    throw std::runtime_error{
        "Error getting your home directory path (pw_dir).\n"
        "Please file a bug report at "
        "https://github.com/JoseExposito/touchegg/issues"};
  }

  return std::filesystem::path{workingDir};
}
```

And from there change the rest of the paths to not assume `.config/`. Changing the default path in `getSystemConfigFilePath` may be a little more involved. I'm working on theory here.

What do you think? I can open a PR for the changes I've made if I get around to actually trying to build this and test it on my laptop.

**Comment by JoseExposito** [comment]
Hi!

About `/etc` vs `/usr`:

I think that `/usr` is the right place, at least in distros like Debian/Fedora/Arch.
However, if you want to use a different prefix, you can:

```
cmake -DCMAKE_INSTALL_PREFIX=/opt -DCMAKE_BUILD_TYPE=Release ..
```

A similar option is available for Touché, in case you want the GUI to be compatible:
https://github.com/JoseExposito/touche/blob/master/meson_options.txt#L13


About `XDG_CONFIG_HOME`: It makes sense, but I need to check that the variable is properly set in the distros I support before introducing the change to make sure I don't break some random distro.

**Comment by elais** [comment]
The issue for me here is at compile time, the app will store everything in a path like `/gnu/store/long-hash-touchegg-0.0.0/` and then symlink the contents of the subdirectories there to `/etc`, `/lib`, `/share` and other base directories present in a profile at runtime, this is how nix and guix achieve reproducible system profiles.

This is the first time I've written C++ before but I created a pull request for the changes I want. In short I changed the paths file to check the XDG directories before reverting to the default settings as they existed before the change. Take a look at it and let me know what changes I need to make, if any.

**Comment by JoseExposito** [comment]
> The issue for me here is at compile time, the app will store everything in a path like /gnu/store/long-hash-touchegg-0.0.0/ and then symlink the contents of the subdirectories there to /etc, /lib, /share and other base directories present in a profile at runtime

So, if you set the prefix to, `/etc`, even though the app is installed in `/gnu/store/long-hash-touchegg-0.0.0/`, it'll look for configuration file in `/etc`. Why this doesn't work?

It seems to work on nixOS. A couple of nixOS contributors created a pull request a month ago and the solution seems to work for them: https://github.com/JoseExposito/touchegg/pull/467

> This is the first time I've written C++ but I've created a pull request for the changes I want

Cool, thanks for your PR.  I can not accept the changes to use `XDG_CONFIG_DIRS`, because its value is not useful in most distributions. I need to check what's the value of `XDG_CONFIG_HOME` before I merge your PR.

**Comment by elais** [comment]
No the app will look for configuration in `/gnu/store/long-hash-touchegg-0.0.0/etc/touchegg/touchegg.conf`, which will be symlinked to the system's `/etc/touchegg/touchegg.conf`. The problem that arises here is that if I want to put a different configuration in the system's `/etc/touchegg/touchegg.conf`, it will get replaced by `/gnu/store/long-hash-touchegg-0.0.0/etc/touchegg/touchegg.conf` the next time I reconfigure my system with `guix system reconfigure` or in nix's case `nixos-switch`.

If the $XDG_CONFIG_DIRS variable solution I've submitted is useful in some distributions and does not break existing functionality is there a reason not to use it? I'm willing to make any changes you want me to.

Alternatively would you be open to adding a flag that sets touchegg's configuration file at runtime? Say `touchegg -c path/to/config/file.conf`?

**Comment by tecosaur** [comment]
Hello Jose!

I've had my eye on this project for a while and I really like what it's doing :smiley:. However, reading this issue I suspect there may be a minor misconception going on with XDG. @elais opened this issue because he uses a rather niche distro where following the XDG spec is particularly important, but it's actually relevant to the vast majority of distros. [Debian](https://wiki.debian.org/XDGBaseDirectorySpecification), [Fedora](https://fedoraproject.org/wiki/Features/XdgConfigDirs), [Arch](https://wiki.archlinux.org/index.php/XDG_Base_Directory), [and more](https://repology.org/project/xdg-user-dirs/versions) all aim to be XDG-compliant.
>Debian does not require that packages conform to the XDGBDS but strongly encourages upstreams to do so

Given that the provided patch uses the current dirs as a fallback when the relevant XDG vars are not defined, it seems a really good idea to me.

**Comment by JoseExposito** [comment]
Hi! Thanks for your comment guys

> No the app will look for configuration in /gnu/store/long-hash-touchegg-0.0.0/etc/touchegg/touchegg.conf, which will be symlinked to the system's /etc/touchegg/touchegg.conf. The problem that arises here is that if I want to put a different configuration in the system's /etc/touchegg/touchegg.conf, it will get replaced by /gnu/store/long-hash-touchegg-0.0.0/etc/touchegg/touchegg.conf the next time I reconfigure my system with guix system reconfigure or in nix's case nixos-switch.

I believe this is the right behaviour. If you want to override your system settings, you should do it for you user, in your home directory.

In case you want to package Touchégg with different defaults, you can patch the configuration I ship upstream to fit your distro needs.

I have never packaged an app for GNU Guix, but most package solution (deb, rpm, PKGBUILD) support patching source code files.

For example, this is how it is shipped on elementary OS because, by default, I provide a GNOME friendly configuration that doesn't make sense in other desktops.
I believe this is the case for pi-topOS. Their main way to interact with the device is a touchscreen and I think they patch upstream config to fit their needs.

Could this solution work for you?

> Debian, Fedora, Arch, and more all aim to be XDG-compliant.

Yes, and I think it is great, and as I mentioned, I'm open to include a patch to use `XDG_CONFIG_HOME`.
I checked the value of `$XDG_CONFIG_HOME` in Ubuntu, elementary OS, Fedora 33/34 and Arch and it is empty for all of them. So there is no risk to break existing installations with this change.

However, adding support for `XDG_CONFIG_DIRS` is a different think.

On one hand because I think that the current behaviour on nixOS/GNU Guix makes sense. The program is installed in the prefix you set and then linked to the most common paths. If you want to override the default settings, you can do it for your user without affecting everyone.

On the other hand because implementing `XDG_CONFIG_DIRS` requires changes in Touchégg, [Touché](https://github.com/JoseExposito/touche), [X11 Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures), [Gala](https://github.com/elementary/gala) and [elementary OS settings](https://github.com/elementary/switchboard-plug-mouse-touchpad) and I need to implement, test and coordinate the releases for all of them, so it is quite a lot of work.

It is not that I don't want to accept the patch because I'm mean, it is because a lot of apps could break changing this, so I prefer to explore other solutions before I break a bunch of people installs.

**Comment by elais** [comment]
I was looking over the other apps you listed because I'm a masochist and I understand your concern but none of these changes would be too disruptive. In fact using the xdg base spec apis available in the various apps would still hit the `/usr/share/touchegg/touchegg.conf` file. For instance this in the Touché repo

```javascript
/**
 * @returns {string} System config file path (/usr/share/touchegg/touchegg.conf).
 */
export const getSystemConfigFilePath = () => process.env.SYSTEM_CONFIG_FILE_PATH;
``` 

Could become something like this 

```javascript
/**
 * @returns {string} System config file path (/usr/share/touchegg/touchegg.conf).
 */
export const getSystemConfigFilePath = () => 
GLib.get_system_config_dirs()
  .concat(GLib.get_system_data_dirs())
  .filter(dir => GLib.file_test(`${dir}/touchegg/touchegg.conf`))[0] 
    || '/usr/share/touchegg/touchegg.conf'
```

The api to get the xdg directories is already present in glib, and `/usr/share` is one of the xdg data dirs. So the config should be picked up regardless if the xdg paths exist. While I understand you do not want to break existing installs due to how this will effect everybody, I think it will be great moving forward to not assume the user or machine's filesystem setup and try to follow their xdg defined paths first if they exist. This way rather than getting another annoying issue from someone running a meme distro you can just say you follow the xdg spec which is encouraged by most linux distros.

If you don't want to do it I'm more than willing to make the changes to your downstream repositories as well, I do js at $DAYJOB and I'm pretty sure that snippet I wrote works, and with the exception of the vala one I'm sure I can get your projects xdg compliant and not reliant on hardcoded paths.

**Comment by JoseExposito** [comment]
Hi!

Thanks for looking into those. As you mentioned, the implementation is not difficult. I'm more worried about compatibility than about complexity.

I still don't know why the current approach doesn't work on GNU Guix. As I mentioned in my previous comment, you are not supposed to edit the system level file. Any change made to that file is and will be ignored by Touché, X11 Gestures & co.

Your home configuration file takes precedence over the system one and this is the only method supported to override your settings.

If Guix reset the system config when you reconfigured it, I think it is fine, because that it the fallback config, not the one you are suppose to configure. If you want to override it, home is the right place. If you want to back it up, there are great tools to do it like dotfiles.

I just wanted to clarify this because of: 

> The problem that arises here is that if I want to put a different configuration in the system's /etc/touchegg/touchegg.conf, it will get replaced by /gnu/store/long-hash-touchegg-0.0.0/etc/touchegg/touchegg.conf the next time I reconfigure my system with guix system reconfigure or in nix's case nixos-switch.

It seems like you are trying to use the extra paths `XDG_CONFIG_DIRS` provides to apply your settings instead of using `~/.config`.

------------------------

Said that, after looking at the [docs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables), `XDG_CONFIG_DIRS` looks like the right variable to use:

> $XDG_CONFIG_DIRS defines the preference-ordered set of base directories to search for configuration files in addition to the $XDG_CONFIG_HOME base directory. The directories in $XDG_CONFIG_DIRS should be seperated with a colon ':'.
>
> If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used.

The word "configuration" instead of "data" is key. Let's compare it with `XDG_DATA_DIRS`:

> $XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'.
>
> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.

According to the docs, the fallback dir for `XDG_CONFIG_DIRS` must be `/etc/xdg`. If we fallback to `/usr/share/` in code, we are not following the spec.

However, the current settings are placed in `/usr/share/` so the options are:

- Use `XDG_DATA_DIRS` instead of `XDG_CONFIG_DIRS`. This breaks the spec because we are looking for config, no data

- Use `XDG_CONFIG_DIRS` but fallback to `/usr/share/` breaking the spec 

- Move the config file to `/etc/xdg` so we follow the spec but break every existing installation... And I mean, the first version of Touchégg was released in 2011 and the config was in `/usr/share/`. I'm sure nobody is using a version that old, but I wouldn't like to break it 10 years later

So, our options are not very good here... Ideas?

**Comment by elais** [comment]
> I still don't know why the current approach doesn't work on GNU Guix. As I mentioned in my previous comment, you are not supposed to edit the system level file. Any change made to that file is and will be ignored by Touché, X11 Gestures & co.

The reason I'm bellyaching over the use of the xdg directories for the system-wide config is because in addition to packaging touchegg (which I've already done elsewhere) I would also like to install it as a shepherd service in guix. Having touchegg point to a directory prepended by an xdg environment variable instead of a hardcoded location when looking for its configuration would allow the config to be replaced by one that lives by itself in the store.


What makes touchegg particularly attractive here is its configuration is in XML. For the guix service the configuration could be defined inline using SXML (a scheme DSL to create XML) and put into a file-like object that will symlink into `XDG_CONFIG_DIRS` at run time, which is how most (all?) services handle configuration. The nix guys have it a little easier than us guix guys because they can just consume the systemd file that comes with touchegg and don't have to create a separate systemd service to use it as one. We on the other hand would have to create a service and exposing touchegg system configuration for modification would be a very nice touch. So yeah, I mostly want that path changeable to continue my petty little system configuration efforts. Hard coding the configuration path at compile time frustrates that effort for me.

> So, our options are not very good here... Ideas?

I would honestly break the spec (slightly) considering touchegg is a project that's been around for a long time. A point in support of this is an even older project: emacs. Emacs's load-path looks for user configuration in three places by default: `$HOME/.emacs`, `$HOME/.emacs.d` and `$XDG_CONFIG_HOME/emacs`. The first two locations are kept around for legacy reasons (it is 40 year old software afterall) but the last location was added so that users could have their xdg directory respected. In the case of touchegg, the old way is there, it exists, and there are systems that depend on it continuing to have a configuration file in `/usr/share/touchegg`. So no matter what happens I believe the old configuration directory should continue to be searched. My solution above is ideal for this. If you would like to put the configuration in a new path going forward that's xdg compliant then hopefully it won't break installs. But ultimately I think the best solution is to *respect* the xdg specification even if touchegg doesn't get around to adhering to it strictly.

**Comment by JoseExposito** [comment]
Cool, thanks for clarifying it. That's a fair use case, let's look into that PR!

**Comment by JoseExposito** [comment]
Fixed in https://github.com/JoseExposito/touchegg/pull/535
