### ISSUE TITLE
Animate going back in browser

### ISSUE THREAD

**Issue by daljit97** [JoseExposito/touchegg#484]
Hi, would it possible to use the animation for changing desktops to for example animate a gesture to trigger going back or forward in Firefox? Currently, I'm assigning a keyboard shortcut (Alt + Left or Alt + Right) to trigger this action in Firefox but I was wondering if it was possible to animate this. In other words, I'm asking if it's possible to tie the animation for changing desktops to the command for sending key events.

**Comment by JoseExposito** [comment]
Not at the moment. This'd require some changes in the current animation -because the arrows are displayed in the edges of the screen, not in the edges of the window- as well as a dedicated action.

I'll tag it as enhancement and leave it open for a while just in case someone wants to implement it. However, to be fair, this should be implemented in the browser, not here. It is perfectly possible to implement it in Firefox or Chrome and the user experience will be much better and also portable to Wayland.

**Comment by daljit97** [comment]
@JoseExposito thanks. I think Firefox developers said they are going to implement this, but I'm pretty sure that they will do so in Wayland only. So this "hack" might be nice for X11.

**Comment by JoseExposito** [comment]
Cool, I didn't know about it, I'm glad they are finally implementing it.
 
I don't know how they plan to implement this, but, if they are going to use a 2 finger swipe, it is perfectly possible to get it working on X11, as it uses scroll events instead of "gesture" events. This is how libhandy works.
