### ISSUE TITLE
Very high gesture sensitivity under X11 after GNOME 40.1 update in Fedora 34

### ISSUE THREAD

**Issue by amitanilkulkarni** [JoseExposito/touchegg#493]
I'm using X11 Gestures extension on GNOME 40.1 / Fedora 34.

After a recent update, the swipe gesture sensitivity has increased a lot, making it unusable under X11.
Wayland gestures work fine as expected, so it seems like an issue with touchegg.

Similar reports on this Reddit thread: https://www.reddit.com/r/gnome/comments/nejq6f/change_x11_gesture_sensitivity/

❯ gnome-shell --version
GNOME Shell 40.1
❯ libinput --version
1.17.2
❯ touchegg --version
Touchégg v2.0.9.

Let me know if any more details are required.

**Comment by JoseExposito** [comment]
Hi!

Thanks for the bug report. This is indeed a problem with Touchégg, it is related to:
https://github.com/JoseExposito/touchegg/issues/489

I thought it was something introduced by GNOME Shell 40.1... But the issue was that I was running a compiled version of libinput.

Long story short:

Fixed on GNOME Shell X11Gestures version 8:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/8

And update will be available in the following, but you can install it from zip now if you want to test it now.

**Comment by amitanilkulkarni** [comment]
Tested out the zip, it works perfectly well with the fix.
It also seems to fix some minor annoyances I had with multiple swipes made in quick succession.

Thanks a lot!
