### ISSUE TITLE
System deamon not starting at reboot.

### ISSUE THREAD

**Issue by mcoyle1960** [JoseExposito/touchegg#515]
Downloaded, built and installed Touchegg v 2.0.11. After installation, the deamon does not appear to be starting after boot. I can start it manually with:

sudo systemctl daemon-reload && sudo systemctl restart touchegg

```
$ touchegg --debug
Touchégg v2.0.11.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/coyle/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
---
### Your environment

Touchégg v2.0.11.
Ubuntu Impish Indri (development branch)
Gnome 40.2.0
X11
```

**Comment by JoseExposito** [comment]
That's weird, the daemon should start automatically with the process you described.

My recommendation is to use the official PPA:
https://github.com/JoseExposito/touchegg#ubuntu-debian-and-derivatives

Or the deb package instead of compiling it yourself.

Let me know if the issue persist after using the PPA and I'll look into it.

**Comment by mcoyle1960** [comment]
I apologize. I woke up this morning and it's working as expected. One of the marvels of Linux. 

Thanks for all your hard work. I love touchegg.

**Comment by JoseExposito** [comment]
No problem! Thanks for closing the issue.
