### ISSUE TITLE
Add velocity of swiping to reflect repetition of keystrokes

### ISSUE THREAD

**Issue by peterkuykendall** [JoseExposito/touchegg#527]
### Is your feature request related to a problem? Please describe
# Problem
I'd like to swipe further than one keystroke or click at a time.

# Proposed solution
Have an option where the velocity of the swipe is measured and if it is fast, repeat the keypress (or action) proportionate to the speed of the swipe.
For example, mapping the 3 finger swipe to the left or right to Ctrl-Tab / Ctrl-Shift-Tab switches changes the chrome tabs to the left or right tab.  With this, if the swipe is hard, it would skip through a number of tabs, possibly even to the first or last tab.

### Describe alternatives you've considered
- simple implementation le is just a linear repetition
- more sophisticated UX would be some parabolic reduction in speed
- requiring a setting (and an entry form) for the speed may be avoided by using some factor/multiplier of the mouse speed setting -- would have to play with this to see what's reasonable
-  the tab example doesn't work for getting to the start/end tab because those keypresses actually loop instead of stop at the end.  It's not necessary to stop at the end tab (for example).

### Additional context
n/a

**Comment by JoseExposito** [comment]
> simple implementation le is just a linear repetition

The current implementation uses unaccelerated movement deltas and linear repetition, 10 repetitions for each swipe.

I could use accelerated deltas, but using them has proved to work poorly in certain situations and at this point it'll break other projects that rely on Touchégg, like Gala.

What's your use case for this? You should be able to switch between 10 Chrome tabs in one swipe, is it not enough in your case? I think I have to say no to this feature because the side effects in other projects but if the use case is fair I can try to implement it.
