### ISSUE TITLE
Make pinch to zoom in and out smooth

### ISSUE THREAD

**Issue by titojankowski** [JoseExposito/touchegg#529]
Thanks for all that you do! It's amazing what you're doing to support gestures.

### Is your feature request related to a problem? Please describe

I'm frustrated when I use Touchegg and I pinch to zoom in or out and it doesn't trigger. And then, when it does trigger, it's jerky as it's just replicating zoom in and zoom out keyboard commands.

### Describe the solution you'd like
I'd love the zooming in and zooming out gestures to work in browsers and photos as smoothly as they do on Mac OS.

### Describe alternatives you've considered

My alternative is just leaving Touchegg off and having no gestures on my trackpad. It's less frustrating.

### Additional context
Context: I'm not a developer, just a regular user. Coming from a Mac, so I'm used to silky smooth zooming in and out of webpages and photos. I've got touchegg setup to replicate ctrl-plus and ctrl-minus on Brave. It triggers about 25% of the time when I use the gesture. Even when it works, it's pretty jerky. 

I also don't care about any other gestures, just zooming in and out. I'm aware of the other gestures coming from a Mac but never found them useful (three finger or four finger)

I'm using Touchegg on PopOS on a System76 Lemur Pro lemp10 laptop.

**Comment by JoseExposito** [comment]
Hi @titojankowski 

Thanks for your bug report.

I'm sorry to hear that you are experimenting issues trying to pinch.

There are 2 main reasons causing the issue and, unfortunately, there is not an easy solution:

- Touchégg uses [libinput](https://gitlab.freedesktop.org/libinput/libinput/) under the hood to recognize pinch gestures. Recently, pinch recognition [was improved](https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/584) making it a bit easier to perform the gesture. If you are using lininput >= 1.18.0, you should have the improved pinch detection code, otherwise, you'll have to wait a bit until Pop!_OS ships the updated packages:
```
$ libinput --version
1.19.0
```
- Touchégg can only send keyboard shortcuts, creating a discrete scroll experience, rather than a smooth experience, like in macOS. Applications should implement pinch to zoom for a better experience and not rely on 3rd party tools like this one. We are slowly getting there, but there is still work to do.

I'm sorry I can not help you a bit more with this issue, but at the moment this is the best I can do :S  

Closing the issue as I can't really fix it, but feel free to ask any questions you might have.

Best wishes,
Jose

**Comment by titojankowski** [comment]
Thanks for all the work you do, @JoseExposito! This is neat to see how these updates propagate through open source and into Pop OS.

I understand the part about libinput, I have heard about this package before. Regarding applications implementing pinch to zoom, surprising it has to be done at an application level. Is there anyone working on this OS-wide?

**Comment by JoseExposito** [comment]
> Regarding applications implementing pinch to zoom, surprising it has to be done at an application level. Is there anyone working on this OS-wide?

The main stopper has been that X11 (the "legacy" windowing system) used to support gestures (about 10~11 years ago) through the [Canonical Multitouch project](https://launchpad.net/canonical-multitouch) but the technology never took off.

You can see a 10 years old version of Touchégg there, as I was one of the users of that technology back in the day.... One of the few users. Unfortunately the technology wasn't broadly adopted and it was abandoned.

For a bunch of years there has not been native X11 support for gestures until very very recently. A new (and better) implementation of gestures on X11 is on its way and I hope this time it is widely adopted. 

Of course, Wayland (the protocol powering the new windowing system) supports gestures, but it is not easy/possible to run it in nvidia hardware. Google it if you want some drama :laughing: 

We are getting really close to OS-wide support but for the moment, we'll have to wait a bit. Hopefully, this time it won't take us 10 years.

**Comment by JoseExposito** [comment]
@gmile sure, check the change log of xf86-input-libinput 1.2.0:

https://lists.x.org/archives/xorg/2021-September/060772.html

"Implement support for touchpad gestures"

I am not sure about the state of it, but I think that all the pieces are there for frameworks/apps to take advantage of them on X11.

**Comment by rwjack** [comment]
Grave digging here, but I was amazed how good the apple magic trackpad 2 worked on Pop OS out the box, until I tried it on Windows.

Feels like Windows is light years ahead regarding trackpad support :c

Anyone managed to get the MacOS 2 finger pinch-zoom gesture to work on X11? I'm stuck on it because of nvidia..
