### ISSUE TITLE
Two finger pinch is often mis-recognised as two finger swipe.

### ISSUE THREAD

**Issue by dreirund** [JoseExposito/touchegg#541]
### Describe the bug

Two finger pinch is easily misinterpreted as two finger swipe.

### Expected behaviour

Make it easier to issue pinch gestures.

Looks like pinch recognition is too "strict".

Make a pinch if the relative distance between the fingers, or the angle of the line between the fingers, changes significantly, also if one finger does not move much absolutely.

Best: Add configuration items on thresholds to tell pinch and swipe apart.

### Actual behaviour

I have two finger pinch and two finger swipe gestures configured. However, if I want to pinch, very easily `touchegg` does a swipe instead.

For three fingers this problem also appears, but less often.

I had the impression that with Touchégg version 1 it was much easier to actually trigger a two finger pinch correctly while also beeing able to trigger two finger swipe.

I use a touchscreen, not a touchpad. It is often just not easy to move both fingers at the same speed in opposite directions; often one finger does not move much but the other does.

### Your environment

 * Version of Touchégg: Run `touchegg --version` in the terminal to check the version: *`Touchégg v2.0.11.`.*
 * Operating System: Ubuntu, Fedora, Arch Linux...: *[Artix GNU/Linux](http://artixlinux.org/)*.
 * Desktop Environment: Gnome, KDE, Xfce...: *No full blown desktop environment. Standalone window manager: `xfwm4` or `openbox`; standalone Panels: `xfce4-panel`.*
 * Multitouch device: *Lenovo m14t touchscreen.*

**Comment by JoseExposito** [comment]
I just released [v2.0.12](https://github.com/JoseExposito/touchegg/releases/tag/2.0.12) including improvements on pinch detection.

Once it is available for your distro, could you test if the new version improved 2 finger pinch detection, please?

If not, a libinput record will help me to reproduce the issue locally. In order to generate one, execute this command:

```bash
$ sudo libinput record > recording.yml
```

And perform a pinch gesture. If the pinch is buggy, press control+C and attach the file here. Otherwise, press control+C and restart the command to keep the log as short as possible.
