### ISSUE TITLE
 How to support single finger swipe gesture and edge gesture recognition

### ISSUE THREAD

**Issue by ironmanpeng** [JoseExposito/touchegg#552]
Does it support single finger swipe gesture and edge gesture recognition? If not, how can I implement it. Thank you very much for providing some ideas!!!

**Comment by JoseExposito** [comment]
Hi

No, 1 finger swipe is not supported because on touchpads it's used to move the mouse pointer and on touchscreens, depending on the context to scroll, drag&drop, select items, etc.
Because 1 finger movement is such a core functionality, it doesn't make sense to override it's behavior on Touchégg.

About edge scrolling, while possible, it'll come with it's own set of bugs because many touchpads doesn't have a know size. In those cases libinput will fallback to a default size and edge detection wouldn't be precise.
However, as I mentioned, it is possible to implement it, if you feel brave, pull requests are very welcome :)

**Comment by JoseExposito** [comment]
Oops, you asked for a little guidance to implement it. If you've looked into Touchégg code, you probable have noticed that it follows a client/sever architecture.

The server is a systemd daemon and it's the bit that "speaks" with libinput. You'd need to get the touch position and the touchpad size here and send it to the client.

The client, would need to receive that information, check if it is a edge swipe, check in the config there is an action associated with it and run it. If no action is associated, falling back to a non-edge swipe makes sense.

In addition, the corresponding setting would need to be added to [Touché](https://github.com/JoseExposito/touche) for this PR to be accepted.

Finally, have in mind that there are multiple Touchégg clients, like the [X11 Gestures GNOME Shell extension](https://github.com/JoseExposito/gnome-shell-extension-x11gestures) and elementary's window manager [Gala](https://github.com/elementary/gala). Any change made in the client/server communication must be backwards compatible, otherwise, those projects would need to be updated as well.

**Comment by ironmanpeng** [comment]
Hi

Thank you very much for your reply. The ideas you provided are very helpful to me. Thanks again.
