### ISSUE TITLE
Crashes almost every boot

### ISSUE THREAD

**Issue by heynnema** [JoseExposito/touchegg#566]
Ubuntu 21.10

touchegg crashes almost every boot

version 202201222146-stable-2.0.13~ubuntu21.10.1

touchegg crashed with SIGABRT (from the .crash log)

What other info can I provide?

**Comment by JoseExposito** [comment]
Hi and thanks for your bug report.

I guess you are using GNOME and you are seeing a notification of the crash?

After the crash, does Touchégg start working after 5-10 seconds? Or do you have to manually restart it?

After the crash, if you run `touchegg --debug` in the terminal, what's the output?

Also, please make sure you are in the X11 session, Touchégg won't work in the Wayland session:
https://github.com/JoseExposito/touchegg#does-touch%C3%A9gg-work-on-wayland

**Comment by rprinsen** [comment]
I have the same issue. Right after logging in, it shows the crash dialog.
Touchégg keeps working though. 

running touchegg --debug shows the same crash report dialog though. 
Could it be that touchegg is started twice at boot? Is there a way to check that?

**Comment by JoseExposito** [comment]
Hi @rprinsen 

Could you share the output of `touchegg --debug`, please?

Also, the output of `sudo journalctl -u touchegg -b` would be helpful.

**Comment by rprinsen** [comment]
For sure, here's the output of journalctl:

mrt 30 18:32:40 rienk-XPS-15-9570 systemd[1]: Started Touchégg Daemon.
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Touchégg v2.0.13.
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Starting Touchégg in daemon mode
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Starting daemon server...
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Generating D-Bus introspection data
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Creating D-Bus server
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Server started at address unix:abstract=touchegg
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: A list of detected compatible devices will be displayed below:
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]: Compatible device detected:
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]:         Name: SYNA2393:00 06CB:7A13 Touchpad
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]:         Size: 102.333mm x 77.3333mm
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]:         Calculating start_threshold and finish_threshold. You can tune this values in your service file
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]:         start_threshold: 30.4462
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]:         finish_threshold_horizontal: 362.598
mrt 30 18:32:40 rienk-XPS-15-9570 touchegg[1197]:         finish_threshold_vertical: 274.016
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: terminate called after throwing an instance of 'std::runtime_error'
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]:   what():  Error initialising Touchégg: libinput open.
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: Touchégg should be run in daemon mode by systemd in order to be part of the 'input' group and have access to your touchpad.
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: If you prefer to run Touchégg without using systemd, please execute the following command:
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: $ sudo usermod -a -G input $USER
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: And reboot to solve this issue
mrt 30 18:32:44 rienk-XPS-15-9570 systemd[1]: touchegg.service: Main process exited, code=dumped, status=6/ABRT
mrt 30 18:32:44 rienk-XPS-15-9570 systemd[1]: touchegg.service: Failed with result 'core-dump'.
mrt 30 18:32:49 rienk-XPS-15-9570 systemd[1]: touchegg.service: Scheduled restart job, restart counter is at 1.
mrt 30 18:32:49 rienk-XPS-15-9570 systemd[1]: Stopped Touchégg Daemon.
mrt 30 18:32:49 rienk-XPS-15-9570 systemd[1]: Started Touchégg Daemon.
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: Touchégg v2.0.13.
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: Starting Touchégg in daemon mode
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: Starting daemon server...
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: Generating D-Bus introspection data
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: Creating D-Bus server
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: Server started at address unix:abstract=touchegg
mrt 30 18:32:49 rienk-XPS-15-9570 touchegg[2496]: A list of detected compatible devices will be displayed below:
mrt 30 18:32:51 rienk-XPS-15-9570 touchegg[2496]: New client connection request
mrt 30 18:32:51 rienk-XPS-15-9570 touchegg[2496]: New client connected
mrt 30 18:32:52 rienk-XPS-15-9570 touchegg[2496]: New client connection request
mrt 30 18:32:52 rienk-XPS-15-9570 touchegg[2496]: New client connected
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]: Compatible device detected:
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         Name: Apple Inc. Magic Trackpad 2
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         Size: 161.957mm x 115.114mm
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         Calculating start_threshold and finish_threshold. You can tune this values in your service file
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         start_threshold: 45.3203
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         finish_threshold_horizontal: 573.865
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         finish_threshold_vertical: 407.883
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]: Compatible device detected:
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         Name: SYNA2393:00 06CB:7A13 Touchpad
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         Size: 102.333mm x 77.3333mm
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         Calculating start_threshold and finish_threshold. You can tune this values in your service file
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         start_threshold: 30.4462
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         finish_threshold_horizontal: 362.598
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]:         finish_threshold_vertical: 274.016
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]: libinput error: event21 - Apple Inc. Magic Trackpad 2: kernel bug: Touch jump detected and discarded.
mrt 30 18:32:55 rienk-XPS-15-9570 touchegg[2496]: See https://wayland.freedesktop.org/libinput/doc/1.18.1/touchpad-jumping-cursors.html for details

**Comment by rprinsen** [comment]
when running touchegg --debug it complains there's already a instance running, which checks out because systemd restarts the service

**Comment by JoseExposito** [comment]
Thanks for the logs. Touchégg runs in 2 different processes, the systemd daemon and the client. It looks like the daemon is crashing and probably displaying the notification in GNOME:

```
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: terminate called after throwing an instance of 'std::runtime_error'
mrt 30 18:32:43 rienk-XPS-15-9570 touchegg[1197]: what(): Error initialising Touchégg: libinput open.
```

I'll try to add more logs and reproduce the error here to see if I manage to figure out why it is crashing.

Thankfully, the daemon is automatically restarted after a crash, so it keeps working... But the annoying notification is displayed :S

**Comment by JoseExposito** [comment]
Hi again @rprinsen, I pushed a fix for this issue to the master branch in case you want to test it.

I'll try to release a new version soon including it :+1:

**Comment by JoseExposito** [comment]
Good to know. I found it easier to reproduce after adding and removing a few input devices. Hopefully once the new release is out you won't experiment more crashes. Let me know if you keep seeing them.

**Comment by rprinsen** [comment]
Thanks for the quick fix @JoseExposito!
I'll wait for the new release to be available through the ppa (i see you did a release just now :+1: )

Will let you know the results!
