### ISSUE TITLE
If else logic in output behaviours

### ISSUE THREAD

**Issue by MiguelGuthridge** [JoseExposito/touchegg#572]
### Is your feature request related to a problem? Please describe

For some kinds of controls, having a single action bound to the gesture doesn't offer enough complexity to allow for the behaviour to be as logical as possible.

### Describe the solution you'd like

It would be great to have a way to map controls to different actions depending on window states and the like.
* Whether the current window is full screen, maximised, restored l, etc
* Whether we are currently in the overview or present windows view on KDE
* Whether the app menu is open

This would allow me to create the following example behaviour when I swipe down with 4 fingers:
* If the app is full screen, exit full screen
* If the app is maximised, restore it
* If the app is restored, minimise it
* If there's no active app, open the overview

### Describe alternatives you've considered

Mapping the gesture to a shell script which implements the if-else logic: this would be tedious to create and annoying to maintain, and the fact that it's external to Touchegg's configuration means that it would be more difficult to transfer it between devices.

**Comment by JoseExposito** [comment]
Hi Miguel,

This functionality could be added as a new kind of action (conditional action or similar) that, depending on the status of the window under the cursor or other checks, would execute a different actions.
In addition, a big chunk of the work should go into [Touché](https://github.com/JoseExposito/touche) to allow easily configure it.

> Mapping the gesture to a shell script which implements the if-else logic: this would be tedious to create and annoying to maintain

I agree. Writing it in C++ in a generic way could be even worse. While this would be a cool feature to add, I don't have the energy right now to implement it... But if you feel brave, you can open a pull request. Honestly, I think that a custom script for your needs'd be the best option.

I'm going to close the feature request. Not because I don't think this would be nice to have, mostly because I'd only accept it as a PR.
