### ISSUE TITLE
Apple Magic mouse gesture support

### ISSUE THREAD

**Issue by ayushhroyy** [JoseExposito/touchegg#579]
### Is your feature request related to a problem? Please describe

Magic mouse touch gestures are similar to magic trackpad yet they aren't working as magic mouse doesn't report itself as trackpad, could there be workaround?
### Describe the solution you'd like
Touch gestures working with magic mouse

**Comment by JoseExposito** [comment]
The Magic Mouse surface is a touchpad and it'd be possible to handle it as such.

However, the [Linux kernel driver](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-magicmouse.c) for the Magic Mouse exposes the device as a "normal" mouse. This makes sense, because if the device was handled as a touchpad, touching it with one finger would move the mouse pointer and many other weird think would happen.

This happens at the kernel level, so closing this issue since there is nothing Touchégg could do here.
