### ISSUE TITLE
Feature request: Tip-Tap gesture

### ISSUE THREAD

**Issue by mauriciabad** [JoseExposito/touchegg#608]
### Feature explanation

I'd like to use the Tip-Tap gestures (like the one in Better Touch Tool). 

It's a very simple gesture and very versatile. Let me highlight some of it's benefits:
- In contrast to the swipe, it has a it goes from 0% to 100% instantly, this provides a good UX for actions that have 2 counterparts and are instant, like copy/paste, prev/next song or any keyboard shortcut combination, whereas swipe is great for continuous actions like volume up/down, brightness up/down or movement-related actions.
- It can be performed consecutively very quickly. This is nice for actions that involve moving by steps, like prev/next window or tab.
- It's a natural, easy-to-perform and quick gesture. Making it great for frequent actions, like copy/paste.

Example useful actions that can be assigned:
- :star: Copy/Paste _(imho this is the ideal action, and should come enabled by default)_
- Shift + Tab / Tab keys
- Previous song or next song
- Go to prev/next Tab, Window, Workspace
- Tile window to left or right
- Increase/Decrease volume or brightness
- Remove/Delete keys
- Left/Right arrow keys (or Up/Down)

### What is Tip-Tap gesture?

1. Tap-hold with 1 finger
2. Tap with a 2nd finger
  a. Variant 1: Left
  b. Variant 2: Right

Video: https://www.youtube.com/watch?v=MRhBa3-O3fM

<p align="center">
  <img height="300px" src="https://user-images.githubusercontent.com/12821361/204856832-7d97acad-6cb8-4c28-b60e-3a3b890a5936.gif" />
</p>

**Comment by JoseExposito** [comment]
Unfortunately, it is not possible to implement this gesture at the Touchégg level.

Touchégg uses libinput to get information about the gestures.

Due to the wide variety of hardware we need to support with different capabilities, libinput provides only information about the gesture performed: swipe, pinch or hold.
See https://wayland.freedesktop.org/libinput/doc/latest/gestures.html

The hold gesture might look useful to implement tip-tap gestures, however, the position of the fingers is not provided by libinput, making it impossible to know if the action is a tip-tap left or right gesture or if the fingers are too far away, for example, a thumb and another finger.

So, even though this would be a nice feature to have, it is not possible to implement it at the moment :(
