### ISSUE TITLE
just ppa ?

### ISSUE THREAD

**Issue by xevilstar** [JoseExposito/touchegg#631]
Dear Maintainer,

First of all thanks for the time and effort you put into this project.

I would humbly ask if you could add a non-ppa debian dedicated apt source, since sometimes lately debian and ubuntu have begun to have some little/slight differences, and I would love to have my apt-source clean and without ppa strings.

Kind Regards
Renato Gallo

**Comment by JoseExposito** [comment]
Hi Renato,

You can find a deb package in the releases page in case you don't want to add the PPA. However, you'll need to update the package manually.

My understanding is that a PPA and a custom APT source are pretty similar. Since I can create a PPA without having to pay for my own server, I'll go with that option.

As far as I know, there is not a similar (and free) service for Debian, so for the moment only PPA and deb packages will be the available options.

**Comment by xevilstar** [comment]
you can for free submit your package to the main debian repos and register as its maintainer 

https://www.debian.org/doc/devel-manuals#debmake-doc
