### ISSUE TITLE
Do you have any plans to support Wayland

### ISSUE THREAD

**Issue by luyanfeng** [JoseExposito/touchegg#635]
Do you have any plans to support Wayland？

**Comment by JoseExposito** [comment]
No, because it won't be possible. Wayland doesn't allow to modify other "clients" (i.e.windows) like X11 allows, so a tool like this one is nor possible.

However, Wayland compositors have the capacity to implement their own gestures. For example, GNOME has very nice 3 finger gestures.

Closing the issue as this is not possible to implement.

**Comment by awarewen** [comment]
> Do you have any plans to support Wayland？你有什么计划支持韦兰吗？

Try [lisgd](https://github.com/Ryu-ga/lisgd), works on hyprland.

**Comment by Abdull** [comment]
@JoseExposito , what about touchégg / touché noticibly reporting back to the user (in its logs and in any GUI) that it does not work when detecting running within a Wayland environment? Also the documentation / README.md will only mention at the very end that it requires X11 and does not support Wayland.


I spent more than an hour to figure out what's wrong.

**Comment by JoseExposito** [comment]
@Abdull I added a dialog, hopefully it makes it a bit easier to figure out why some features might not work:

![image](https://github.com/JoseExposito/touchegg/assets/1335948/cdf38780-353b-46a0-ae06-33c3fd69a9f9)
