### ISSUE TITLE
MOUSE_CLICK is limited to first 3 buttons

### ISSUE THREAD

**Issue by haarp** [JoseExposito/touchegg#636]
### Is your feature request related to a problem? Please describe

Mice can have more than 3 buttons. mouse8/9 for example are frequently thumb buttons used for back/forward navigation. Some mice can even have [dozens of buttons](https://i.rtings.com/assets/products/RHxMt456/logitech-g600-mmo-gaming/design-large.jpg). Touchegg only allows clicking 1, 2 and 3. I don't see why this should be a limitation.

### Describe the solution you'd like

Allow arbitrary mouse buttons

### Describe alternatives you've considered

I have tried using `RUN_COMMAND` with `xdotool click 8`, but it seems the Touchegg animation swallows the clicks generated by it (this might be a bug of its own?)

### Additional context

Thanks a lot! This is a great tool and works better than the others I've tried! :)

**Comment by JoseExposito** [comment]
Hi, and sorry for the delay, I've been busy.

I'm not in front of the PC right now, but if I remember correctly, you can set any mouse button if you open the XML configuration.

However, using the GUI (Touché) only left, middle and right buttons are available for simplicity... And because if I add the scroll up/down buttons that would offer a terrible scrolling user experience, so I decided to keep it simple.

Try to change the number manually and let me know if that worked.

**Comment by haarp** [comment]
No worries :)

I'm actually editing the config file directly. I just tried this again and... it works. Weird. I don't remember what I was doing back then, but it does work now. Closing here, sorry for the false alert!
