### ISSUE TITLE
Failed to start touchegg.service - Touchégg Daemon. On Ubuntu 23.10

### ISSUE THREAD

**Issue by omarhammad** [JoseExposito/touchegg#648]
× touchegg.service - Touchégg Daemon
     Loaded: loaded (/etc/systemd/system/touchegg.service; enabled; preset: enabled)
     Active: failed (Result: core-dump) since Fri 2023-10-20 03:16:29 CEST; 13h ago
   Duration: 177ms
    Process: 17460 ExecStart=/usr/bin/touchegg (code=dumped, signal=ABRT)
   Main PID: 17460 (code=dumped, signal=ABRT)
        CPU: 20ms

Oct 20 03:16:29 omarhammad systemd[1]: touchegg.service: Scheduled restart job, restart counter is at >
Oct 20 03:16:29 omarhammad systemd[1]: Stopped touchegg.service - Touchégg Daemon.
Oct 20 03:16:29 omarhammad systemd[1]: touchegg.service: Start request repeated too quickly.
Oct 20 03:16:29 omarhammad systemd[1]: touchegg.service: Failed with result 'core-dump'.
Oct 20 03:16:29 omarhammad systemd[1]: Failed to start touchegg.service - Touchégg Daemon.

**Comment by JoseExposito** [comment]
Could you attach the output of `journalctl -u touchegg -b`, please? Does this happens always or is it a single crash? Does the same error happen if you manually restart the service (`sudo systemctl restart touchegg.service`)?

**Comment by omarhammad** [comment]
It happened after i updated ubuntu from 23.04 to 23.10 
this is the output after  i exectued : journalctl -u touchegg -b
Oct 23 14:21:36 omarhammad systemd[1]: Started touchegg.service - Touchégg Daemon.
Oct 23 14:21:36 omarhammad touchegg[1876]: Touchégg v2.0.17.
Oct 23 14:21:36 omarhammad touchegg[1876]: Starting Touchégg in client mode
Oct 23 14:21:36 omarhammad touchegg[1876]: terminate called after throwing an instance of '>
Oct 23 14:21:36 omarhammad touchegg[1876]:   what():  Error opening your X11 display. Make >
Oct 23 14:21:36 omarhammad systemd[1]: touchegg.service: Main process exited, code=dumped, >
Oct 23 14:21:36 omarhammad systemd[1]: touchegg.service: Failed with result 'core-dump'.
Oct 23 14:21:36 omarhammad systemd[1]: touchegg.service: Scheduled restart job, restart cou>
Oct 23 14:21:36 omarhammad systemd[1]: Stopped touchegg.service - Touchégg Daemon.
Oct 23 14:21:36 omarhammad systemd[1]: Started touchegg.service - Touchégg Daemon.
Oct 23 14:21:36 omarhammad touchegg[2323]: Touchégg v2.0.17.
Oct 23 14:21:36 omarhammad touchegg[2323]: Starting Touchégg in client mode
Oct 23 14:21:36 omarhammad touchegg[2323]: terminate called after throwing an instance of '>
Oct 23 14:21:36 omarhammad touchegg[2323]:   what():  Error opening your X11 display. Make >
Oct 23 14:21:36 omarhammad systemd[1]: touchegg.service: Main process exited, code=dumped, >
Oct 23 14:21:36 omarhammad systemd[1]: touchegg.service: Failed with result 'core-dump'.
Oct 23 14:21:36 omarhammad systemd[1]: touchegg.service: Scheduled restart job, restart cou>
Oct 23 14:21:36 omarhammad systemd[1]: Stopped touchegg.service - Touchégg Daemon.
Oct 23 14:21:36 omarhammad systemd[1]: Started touchegg.service - Touchégg Daemon.
Oct 23 14:21:36 omarhammad touchegg[2568]: Touchégg v2.0.17.
Oct 23 14:21:36 omarhammad touchegg[2568]: Starting Touchégg in client mode
Oct 23 14:21:36 omarhammad touchegg[2568]: terminate called after throwing an instance of '>
Oct 23 14:21:36 omarhammad touchegg[2568]:   what():  Error opening your X11 display. Make >


also the restart is not working with the service

**Comment by capozzid** [comment]
Exact same problem here

**Comment by JoseExposito** [comment]
Something weird is going on, the D-Bus service is trying to start Touchégg in client mode:

```
Oct 23 14:21:36 omarhammad systemd[1]: Started touchegg.service - Touchégg Daemon.
Oct 23 14:21:36 omarhammad touchegg[2568]: Touchégg v2.0.17.
Oct 23 14:21:36 omarhammad touchegg[2568]: Starting Touchégg in client mode
```

The expected output is:

```
Oct 28 11:19:05 fedora systemd[1]: Started touchegg.service - Touchégg Daemon.
Oct 28 11:19:05 fedora touchegg[5542]: Touchégg v2.0.16.
Oct 28 11:19:05 fedora touchegg[5542]: Starting Touchégg in daemon mode
Oct 28 11:19:05 fedora touchegg[5542]: Starting daemon server...
Oct 28 11:19:05 fedora touchegg[5542]: Generating D-Bus introspection data
Oct 28 11:19:05 fedora touchegg[5542]: Creating D-Bus server
Oct 28 11:19:05 fedora touchegg[5542]: Server started at address unix:abstract=touchegg
```

In my distro, the service is installed in `/lib/systemd/system/touchegg.service`. Could you attach the contents of the service file, please? Here is mine:

```
$ cat /lib/systemd/system/touchegg.service
[Unit]
Description=Touchégg Daemon
Documentation=https://github.com/JoseExposito/touchegg/tree/master/installation#readme

[Service]
Type=simple
Group=input
ExecStart=/usr/bin/touchegg --daemon
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

Note the `--daemon` flag in `ExecStart`. Your log suggest that the service is placed in `/etc/systemd/system/touchegg.service`.

**Comment by JoseExposito** [comment]
Oh! And how did you installed Touchégg? From the PPA or deb package?

**Comment by ihtisham-sudo** [comment]
> Oh! And how did you installed Touchégg? From the PPA or deb package?

Installed from deb because PPA was not working from me, Getting this error :
Touchégg v2.0.17.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/ihtishamsudo/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...
